### ISSUE TITLE
Bug report: DNA that you want to translate from start to end has a double translation

### ISSUE THREAD

**Issue by zeroaltitude** [Lattice-Automation/seqviz#101]
To reproduce:

Tell SeqViz to visualize the following sequence in the linear viewer:  TACCAGCAG (YQQ)

Now, add this translation: [{"start":0,"end":9,"direction":1}]

Expected result
```
TACCAGCAG
Y--Q--Q--
```

Actual result:

```
TACCAGCAG
Y--Q--
Y--Q--
```

When translating the entirety of a DNA string, the tool doubles up the translation and does not translate the last element of the AA string. I think that's very counterintuitive. I think it's a bug.

**Comment by zeroaltitude** [comment]
The bug appears to be around here: https://github.com/Lattice-Automation/seqviz/blob/61ba47fcfa133d55ed94f4009f99c3dd4be9d2c5/src/utils/sequence.js#L280

The code is explicitly doubling the DNA sequence for reasons that are slightly opaque to me but probably have something to do with reasoning about plasmids. In the linear case, something about this wraparound is causing an issue.

**Comment by jjti** [comment]
Thanks for the catch

This should be fixed in v3.0.36 with this change: https://github.com/Lattice-Automation/seqviz/commit/73ca3f767b3a45657fcb75e19d6fcfff0c2543f3

I also updated the README to be clearer about ranges. It had said that indices were "inclusive" but the end was actually 0-based "exclusive"

**Comment by zeroaltitude** [comment]
Thank you so much!
