### ISSUE TITLE
Molecular weight

### ISSUE THREAD

**Issue by elizabethmauro** [Lattice-Automation/seqviz#131]
Molecular weight calculation and display

**Comment by jjti** [comment]
Suggestion is to return this in `onSelection`. This is kinda like the contextmenu issue where my 2c is that we should not add this to the viewers, or include its display within the viewers, since consumers of the library will already have a UI/app that can show meta like this. Example is the demo where we have an INFO dropdown that can show meta from `onSelection`: https://tools.latticeautomation.com/seqviz/?backbone=pSB1C3&biobrick=BBa_K1598008

**Comment by jjti** [comment]
I'm gonna close in favor of us asking consumers of the lib to calculate that on selection.

I realize we already return the gc% and tm in the selection (which was probably a bad call / a mistake from when we ported this out of a web app). But if we return some meta about a seq for them, it seems theoretically endless all the diff stats/meta we could digest and return for the user for the given selection/meta. Plus it complicates things if/when we add support for RNA and amino acid sequences
