### ISSUE TITLE
Add Number Of Search Hits

### ISSUE THREAD

**Issue by xKabbe** [Lattice-Automation/seqviz#191]
**Summarize your feature idea. (Why)**

I'm currently working with `seqviz` in a hobby project to practice/learn a bit and am currently dealing with the `search parameter` of the component. If you are searching for a certain sequence, it can be a bit difficult to determine the number of search hits, depending on the total number of nucleotides.

I would have expected that either directly in the component or in the metadata area, a small display regarding the search hits would be available. If it's already implemented and I just can't find it I apologize in advance.

**Describe your preferred solution. (What)**

![2023-02-01_20h11_44](https://user-images.githubusercontent.com/70109596/216142819-81bc8dd0-d00e-48d4-b6dc-96490dd18b71.png)

Would display something like `4 Search hits for 'ATTT'` inside the component/metadata. Another idea was to add another property to the components search parameter to control the display of this little feature:

```ts
search={{ query: 'ATTT', mismatch: 0 }}
```
to
```ts
search={{ query: 'ATTT', mismatch: 0, displaySearchHits: true }}
```

**Comment by jjti** [comment]
Hey @xKabbe,

Thank you for the call out, and I understand the desire to see the total number of search results in a component over the Linear Viewer. I imagine it could be a box that's in the top-left, top-right, bottom-right, or bottom-left of the viewer.

In the past, we had similar requests to show the Tm of sequence selections, dg of sequence selections, etc. 

In general, and as of late, I've opted not to add these higher-level components. That's because each app using SeqViz looks slightly different, so I don't want to hazard a guess at all the font/sizes/formatting/positioning/etc of those meta-components. I've tried to keep the library narrowly scoped to linear/circular sequences+annotations. I hope that makes sense, although it is a bit of an inconvenience. 

Best,
Josh
