### ISSUE TITLE
Ticks in the linear viewer are 1 base off

### ISSUE THREAD

**Issue by cmonnom** [Lattice-Automation/seqviz#278]
**Describe the bug**

Ticks under the sequence in the linear viewer are placed under the wrong base.

For example, the tick labeled "1" is under the 1st base which is at index 0.

**Expected behavior**

Since everything is 0-based, the tick should either start at 0, or (better?) placed between the 1st and 2nd amino acid.

Maybe something like this: 
![image](https://github.com/user-attachments/assets/cd79e5bf-ebff-4d0f-a3ab-aa0874ff0acf)

Rather than the current:

![image](https://github.com/user-attachments/assets/3b6cf9f2-7756-4b51-ad98-3c77d16ab912)

**Screenshots**

![image](https://github.com/user-attachments/assets/ae4abfa2-ab6f-4c3d-832e-5f208a1fb5d2)

**Your environment:**

Windows 11
Chrome 131.0.6778.140

**Comment by jjti** [comment]
Hey @cmonnom, as you've flagged the UI is 1-based while the input/output are 0-based. I'm not sure we can change that now, though, without breaking folks' existing workflows (which would be worse than fixing it). Further, IIRC most tools biologists use are 1-based so that's what the viewers attempt to show: 1-based indexes

Would it help if the demo were fixed? I agree that header being 0-based is strange given all the rest of it.

**Comment by cmonnom** [comment]
Hi @jjti , I think I understand what you mean: SeqViz internals use a 0-based system but what's shown to the user is a 1-based index. (what users of the library have access to are the 0-based start/end).
