### ISSUE TITLE
CDN not working

### ISSUE THREAD

**Issue by gezmi** [Lattice-Automation/seqviz#73]
Hi All,

I would like to use this package via CDN. However, the provided link gives the following error:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>344D8B9144E39E40</RequestId>
<HostId>
FBex/FohCVLEi3j0GjvWRhgpJDKzQxbxlldjRz1oilArV3gEL1S7KfJeTB2SAJg5she9DAE97As=
</HostId>
</Error>
```
Have I misunderstood something and it is only a package for internal use, or is this really an error?

Thank you!

**Comment by JJTimmons** [comment]
Hi @gezmi,

Very sorry about that. Since adding `npm` support I haven't been checking the CDN distribution as I should. I'll look at this today

**Comment by jjti** [comment]
I switched our CDN reference in the README to point to UNPKG. New CDN src is below:

~<script src="unpkg.com/seqviz"></script>~

I forgot the https:// in that src link above:

`<script src="https://unpkg.com/seqviz"></script>`

This should be working in v3.0.10 and above. Please let me if this fixes the issue for you

**Comment by gezmi** [comment]
Hi @JJTimmons ,

Thank you for the answer, the CDN is working. However, I am stil not able to use it. Here is my code:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://requirejs.org/docs/release/2.3.5/minified/require.js"></script>
    <script src="https://unpkg.com/seqviz@3.0.2/dist/index.js"></script>

</head>
<body>
<div id="root"></div>
<script>
    window.seqviz.Viewer("root", {
            name: "L09136",
            seq: "tcgcgcgtttcggtgatgacggtgaaaacctctgacacatgca"
        })
        .render();
</script>
</body>
</html>
```
I included the require.js because without it, te browser gives  `index.js:6 Uncaught ReferenceError: require is not defined`. This way, it gives `Uncaught TypeError: Cannot read property 'Viewer' of undefined`

Thank you for this package and your help!

> I switched our CDN reference in the README to point to UNPKG. New CDN src is below:
> 
> ```
> <script src="unpkg.com/seqviz"></script>
> ```
> 
> This should be working in v3.0.10 and above. Please let me if this fixes the issue for you

**Comment by jjti** [comment]
Because of a bug (my fault), the CDN version of `seqviz` wasn't being deployed in earlier versions (before 3.0.10 version). So I would recommend using the most recent version of `seqviz` as in the example HTML script below.

Also, the file that you're pointing to in the example HTML `https://unpkg.com/seqviz@3.0.2/dist/index.js` is pointing to a version without dependencies. If you use the code below, instead, it should point to a version of `seqviz` CDN with dependencies packaged.

```html
    <!-- points to /dist/seqviz.min.js; latest version by default: 3.0.13 right now -->
    <script src="https://unpkg.com/seqviz"></script>
```

I tested this in `seqviz` and it was working, albeit in a node test environment.

As a side note, I fixed a separate issue on my end involving enzyme recognition sites in the CDN build version. It's resolved in versions >=3.0.12.

**Comment by gezmi** [comment]
Many thanks for your patience, I think I am getting somewhere - at least now I have a different error.
Here is my current code:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.3/runtime.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/seqviz"></script>
</head>
<body>
<div id="root"></div>
<script>
    window.seqviz.Viewer("root", {
            name: "L09136",
            seq: "tcgcgcgtttcggtgatgacggtgaaaacctctgacacatgca"
        })
        .render();
</script>
<script>
    console.log(window.seqviz.Viewer("root", {
            name: "L09136",
            seq: "tcgcgcgtttcggtgatgacggtgaaaacctctgacacatgca"
        })
    );
</script>
</body>
</html>
```

The second Viewer call is for verifying that the object was constructed and it seems to be OK. However, when I call .render(), as in the first instance, I am getting the following error:
```
Uncaught TypeError: Cannot read property 'filter' of undefined                         seqviz.min.js:34 
    at seqviz.min.js:18
    at Sc (seqviz.min.js:34)
    at Pc (seqviz.min.js:34)
    at Xo (seqviz.min.js:34)
    at Ni (seqviz.min.js:34)
    at _u (seqviz.min.js:34)
    at xu (seqviz.min.js:34)
    at bu (seqviz.min.js:34)
    at seqviz.min.js:34
    at e.unstable_runWithPriority (seqviz.min.js:42)
Uncaught TypeError: Cannot read property 'filter' of undefined             seqviz.min.js:18 
    at seqviz.min.js:18
    at Sc (seqviz.min.js:34)
    at Pc (seqviz.min.js:34)
    at Xo (seqviz.min.js:34)
    at Ni (seqviz.min.js:34)
    at _u (seqviz.min.js:34)
    at xu (seqviz.min.js:34)
    at bu (seqviz.min.js:34)
    at seqviz.min.js:34
    at e.unstable_runWithPriority (seqviz.min.js:42)
```

Initially, I would like to include it in a Laravel project. I know that I could use ReactJS, and I managed to get it working in a clean Laravel install, however, not for my already existing project :( Getting the vanilla-js work seemed to be easier.

Thank you for all your help!

**Comment by jjti** [comment]
Hey @gezmi,

Thank you, actually. That was another bug you found. When annotations weren't provided, the React component was defaulting to null where it should have defaulted to an empty array. I'm sorry about that. I added a test case for this scenario (with your example input) and opened an issue (#75) to test a couple more Viewer level rendering scenarios.

Change to fix it below:

![Screen Shot 2020-02-04 at 9 57 36 AM](https://user-images.githubusercontent.com/13923102/73756281-4b46ee80-4735-11ea-8878-0c8491a031f5.png)

Please try again when you get the chance.

**Comment by gezmi** [comment]
Hi @JJTimmons,

I think, I am almost there :) So now it renders the html dom elements, but they cannot be seen, only a blank page (but I get no errors). If I play around with the css class in the browser by turn on/off some (e.g position: absolute, and a couple of others), sometimes it shows both the circular and the linear visualization. Sorry, I cannot replicate what I have turned on/off.

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.3/runtime.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/seqviz"></script>
</head>
<body>
<div id="root"></div>
<script>
    window.seqviz.Viewer("root", {
            name: "L09136",
            seq: "tcgcgcgtttcggtgatgacggtgaaaacctctgacacatgca",
            viewer: "both"
        })
        .render();
</script>
</body>
</html>
```

Thanks!

**Comment by jjti** [comment]
Hey @gezmi,

I can't say for sure, but my guess is that the html element that contains `seqviz` lacks a height/width. It wasn't clear from the README, but `seqviz` expands only to fill the size of its parent element (height and width == 100%). If the parent element doesn't have a fixed, absolute, vh/vw, etc height, `seqviz` won't expand to fill the parent's height at all. We're using [this component](https://github.com/ctrlplusb/react-sizeme) to find the width of SeqViz which is whatever the height of its parent element is.

I just changed SeqViz in a patch in version `3.0.15` to expose an options/prop called "style". It's provided to the highest level container div in SeqViz, and can be used to set the height of SeqViz directly (rather than depending on the container element around SeqViz). The README reflects this new render option, and shows how to have SeqViz expand to fill the entire screen.

```html
<script>
  window.seqviz
    .Viewer("root", {
      name: "L09136",
      seq: "tcgcgcgtttcggtgatgacggtgaaaacctctgacacatgca",
      style: { height: "100vh", width: "100vw" }
    })
    .render();
</script>
```

That being said, I think the best bet is to have size the parent div within the context of the surrounding HTML and let SeqViz expand to fill that parent. I hope this was the issue, but let me know either way. Btw are you server side rendering? If so, I may need to expose another flag/option for [changing the way react-sizeme is used](https://github.com/ctrlplusb/react-sizeme/issues/120).

In near future I'll add a check for when SeqViz detects that it has a zero height or width and throw an error.

**Comment by gezmi** [comment]
Wow, it works :) Thank you very much! I really like the look and functionality of this viewer, thanks for developing!

**Comment by jjti** [comment]
No problem and thanks for bearing with me the on this. I'm glad you like it, let me know, after using it, whether there are any changes you want or features you want adde

**Comment by jzplyy** [comment]
hi, JJTimmons , can more information be shown while mouse hover and viewer set circle , and set the enzymesCustom color?
