### ISSUE TITLE
React component does not re-render when file prop changes

### ISSUE THREAD

**Issue by stropitek** [Lattice-Automation/seqviz#80]
Hello,

Thank you for this really nice plasmid visualization tool.

I noticed that when the `SeqViz` components re-renders with a new `file` property, nothing changes. The first `file` value that was passed is the one getting rendered indefinitely.

This seems like a bug to me.

**Comment by jjti** [comment]
Hey @stropitek thanks for pointing this out and agreed that it's a bug. I'll try to add some tests and fix this by later today

**Comment by jjti** [comment]
@stropitek I believe I found issue, where I wasn't checking for new file props. I pushed a fix that should be available in v3.0.23

<img width="511" alt="Screen Shot 2020-03-16 at 11 23 46 AM" src="https://user-images.githubusercontent.com/13923102/76773405-c78f1180-6778-11ea-9246-51635f4ab3d4.png">

I had some trouble setting up a test w/ enzyme and .setProps because of something like [this issue](https://github.com/facebook/react/issues/15691), which I haven't seen before. Ie the testing is rough, but I'm still pretty sure I fixed what had been the issue here.

Please let me know if you see any more issues

**Comment by stropitek** [comment]
Thanks a lot for the fix! It also seems to me that diff should solve it.

I haven't used enzyme yet so I cannot help you out on this one :/

If I have any trouble with this next time I work on that project I will open another issue.
