### ISSUE TITLE
snapgene file (.dna) not recognized error

### ISSUE THREAD

**Issue by tirumal-c** [Lattice-Automation/seqviz#82]
Thank You for a great tool. Wondering if any one tried using a snapgene file (.dna file) or .fasta file? With iGem part nos. and genback accession nos. it is generating and annotating the map fine. I have not tried other file formats, yet. The error message says that these file formats are not recognised. But, that can't be as the package documentation explicitly puts these two file formats as acceptable. What could be going wrong?  

This is the error message from the console: 
seqviz.min.js:18 Error:  File type not recognized: pUC19.fasta
    at seqviz.min.js:18
    at h (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.t.<computed> [as next] (runtime.js:97)
    at h (runtime.js:45)
    at r (runtime.js:135)
    at runtime.js:170
    at new Promise (<anonymous>)
    at i (runtime.js:169)
    at b._invoke (runtime.js:192)

and for the snapgene file same thing
seqviz.min.js:18 Error:  File type not recognized: pBS001.dna
    at seqviz.min.js:18

From html:
<div id="plasmidMap">
<script>
  window.seqviz
    .Viewer("plasmidMap", {
      file: "pUC19.dna",
      style: { height: "100vh", width: "100vw" }
    })
    .render();
</script>
</div>

**Comment by jjti** [comment]
Hello! Sorry for slow reply. I think the issue here is that the file parameter, right now, doesn't accept a file name. It requires an actual File object: https://developer.mozilla.org/en-US/docs/Web/API/File. I'm not 100% sure, but I don't think browsers can simply access files by name (for security reasons).

Can you pass a File/Blob to the viewer's file parameter? Or, alternatively, set the name and seq manually (on their own)?

**Comment by YichaoOU** [comment]
how to pass a `File object`?

is it correct?

```
<script>
  var file1 = new File(['foo'],"HBBP1-HgG1.dna");
  window.seqviz
    .Viewer("root", {
      file : file1
    })
    .render();
</script>
```
